Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-8.7"
    config.vm.synced_folder "C:\\Users\\James\\Dropbox", "/home/vagrant/dropbox"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4096"
        vb.customize ["modifyvm", :id, "--vram", 256]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end

    # FIXME: Debian equivalent of?
    # virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11

    # Update software, install git (and sudo 'cos debian)
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y && apt-get upgrade -y
        apt-get install -y git sudo
    SHELL

    config.vm.provision "shell", path: '../vagrant.sh', privileged: false
end
