Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.10"
    config.vm.synced_folder "C:\\Users\\James\\Dropbox", "/home/vagrant/dropbox"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4096"
        vb.customize ["modifyvm", :id, "--vram", 256]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end

    # Update software, install virtualbox and git
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y && apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive apt-get disp-upgrade --yes
        apt-get install -y \
            virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11 \
            git
    SHELL

    config.vm.provision "shell", path: "../vagrant.sh", privileged: false
end
