# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
    config.vm.base_mac = "5CA1AB1E0001"

    config.vm.box = "bento/debian-8.7"
    config.vm.synced_folder "C:\\Users\\James\\Dropbox", "/home/vagrant/dropbox"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4096"
        vb.customize ["modifyvm", :id, "--vram", 256]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end

    # FIXME: Debian equivalent of?
    # virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11

    # Update software, install git (and sudo 'cos debian)
    config.vm.provision "shell", inline: <<-SHELL
        freebsd-update fetch
        freebsd-update install
        pkg update
        pkg upgrade
        pkg install bash git sudo
        echo "vagrant ALL=(ALL) NOPASSWD:ALL" > /usr/local/etc/sudoers.d/vagrant
        chsh -s "$(which bash)/bash" vagrant
    SHELL

    config.vm.provision "shell", path: '../vagrant.sh', privileged: false
end
